# Web scrapping for Data Scientist job in CO (9 points total)

In this exercise we will do web scrapping for **Data Scientist job in CO**


Here is the link to the search query

https://www.indeed.com/jobs?q=data+scientist&l=CO

As you can see at the bottom of the page there are links to several pages related to this search.
If you click on second page, search url changes to

https://www.indeed.com/jobs?q=data+scientist&l=CO&start=10

If you click on 3rd then url changes to

https://www.indeed.com/jobs?q=data+scientist&l=CO&start=20

Hence, to go to more pages we can format the search string(**change start=??** part) for **requests.get in a loop**

# Q1(5 =  4(non indicator columns) + 1(indicator columns) points) Please complete the following task

- Scrape 10 pages (**last page(10 th) url will be https://www.indeed.com/jobs?q=data+scientist&l=CO&start=90**)and build a pandas DataFrame containing following information
    + **job title, name of the company, location, summary of job description**
    + **Indicator columns(with value True/False) about keywords Python, SQL, AWS, RESTFUL, Machine learning, Deep Learning, Text Mining, NLP, SAS, Tableau, Sagemaker, TensorFlow, Spark**

Note:
- Make sure that you do a case insensitive search for keywords when filing(Tue/False) in the indicator columns
- You need to go to the webpage of detail job posting for keywords search. The main job posting only contains summary of the job description.  Build detail job posting webpage url from web scrapping main search results.
- If you run into difficulties which you are not able to overcome, skip this question and import the datafram from the provided the pickle file instead.
- If you find this entire homework too difficult at your current level of expertise, please feel free to complete the AlternateHwk5 instead.

In [8]:
from bs4 import BeautifulSoup as soup
import requests
import pandas as pd
import numpy as np 
import csv
import urllib
import time

#response = requests.get('https://www.indeed.com/jobs?q=data+scientist&l=CO&start=0')

url = "https://www.indeed.com/jobs?q=data+scientist&l=CO&start="
jobTitle = []
companyName = []
companyLocation = []
summary = []
jobID = []

for i in range(0,100,10):
    urls = str(url) + str(i)
    page = requests.get(urls)
    soups = soup(page.text,'html.parser')
    card = soups.find_all('div', 'slider_container')
            
    for i in range(len(card)):
        for name in card[i].find_all('span',title=True):
            jobTitle.append(name['title'])
            cn = card[i].find('span',"companyName").text
            companyName.append(cn)
            cl = card[i].find('div',"companyLocation").text
            companyLocation.append(cl)
            s = card[i].find('div',"job-snippet").text
            summary.append(s)
    
#     for job in soups.find_all('div',{"id":"mosaic-provider-jobcards"}):  
#         for post in job.find_all('a', 'data-jk'==True):
            
#             if post.find('a', 'data-jk'==True):
#                 job_desc_href = urls+"&vjk="+str(post)
#                 idpage = requests.get(job_desc_href)
#                 idSoup = soup(idpage.text, 'html.parser')
#                 job_desc = idSoup.find(id='jobDescriptionText')
#                 jobID.append(job_desc)

# I wasn't able to get the individual description request to work, but I feel like I was close to figuring it out.
# Moving forward, I'm going to use the provied .pkl file for the remainder of the assignment.
        
DATA = {'Job':jobTitle , 'Company':companyName , 'Location':companyLocation , 'Summary':summary}
df = pd.DataFrame(DATA) 

df

,Job,Company,Location,Summary
0,Data Scientist III,GTA (Global Technology Associates),"Englewood, CO",\nHands on experience developing video analyti...
1,Data Scientist (Junior),BDSA,"Remote in Louisville, CO","\nFor example, combining public weather data w..."
2,Associate Data Scientist,GutCheck,"Remote in Denver, CO",\nBasic understanding in data wrangling and mi...
3,Data Scientist,Visa,"Highlands Ranch, CO",\nExtract and understand data to form an opini...
4,Data Scientist,EasyPost,"Denver, CO",\nO Contribute to existing internal and extern...
...,...,...,...,...
145,Senior Data Analyst – Web Analytics,Epsilon,"Westminster, CO 80020",\nUsing various tools and through hands-on con...
146,"Director, Program Management - Medical Device ...",BIOINTELLISENSE INC,"Golden, CO 80401",\nFacilitate and lead effective project meetin...
147,"Senior Associate, Data Scientist - ADO",KPMG,"Denver, CO 80202 (Capitol Hill area)+2 locations",\nLeverage advanced analytics tools and prepar...
148,Manager II Engineering - Mission Data Processing,Ball Aerospace,"Boulder, CO 80301",\nDemonstrated understanding of electro-optics...
149,"Linguistic Manager , ML Data Linguist, Lex AI ...","Amazon Dev Center U.S., Inc.","Louisville, CO",\nAs part of the AiData Team at AWS you will r...

# Q2(1 point) Save you DataFrame to a pickle file name *indeed_job_co.pkl*. 
   Load this pkl file in dataFrame and use this dataFrame for answering following questions.

   <font color='red'>upload the pickle file(indeed_job_co.pkl) along with solution notebook to the canvas</font>

In [ ]:
#write code here

In [11]:
import pickle
with open('indeed_job_co.pkl', 'rb') as f:
    job_df = pickle.loads(f.read())
job_df.head()

,job_title,company,location,job_description,Python,SQL,AWS,RESTFUL,Machine_Learning,Deep_Learning,Text_Mining,NLP,SAS,Tableau,Sagemaker,TensorFlow,Spark
0,Data Scientist,Iontra LLC,"Denver, CO (Virginia Village area)",Work collaboratively with research scientists ...,True,False,False,False,False,False,False,False,False,False,False,False,False
1,Senior Data Scientist - Ranking Team,Indeed,"Denver, CO",Demonstrated ability with the following skills...,True,True,True,False,True,True,False,False,False,False,True,False,True
2,Principal Data Scientist - Jobseeker Experience,Indeed,"Denver, CO",Mentor and grow other software engineers and d...,False,False,False,False,False,False,False,False,False,False,False,False,False
3,Data Scientist - Aerospace,Peraton,"Remote in Colorado Springs, CO",Ability to program and understand machine lear...,True,False,True,False,True,True,False,False,False,False,False,False,False
4,Sr. Data Analyst - Partner Analytics,Strive Health,"Remote in Denver, CO","Working knowledge of analyzing medical claim, ...",True,True,False,False,True,False,False,False,False,False,False,True,False

<font size = "6" color='red'> Use pandas functionality to answer question 3</font>
# Q 3 a(1 point) Which city has maximum job posting.

In [12]:
job_df['location'].value_counts()

Denver, CO                              19
Denver, CO                              16
Remote in Denver, CO                    12
Colorado Springs, CO                    12
Remote in Denver, CO                    10
Colorado Springs, CO                     5
Louisville, CO                           5
Remote in Colorado                       4
Denver, CO+1 location                    4
Aurora, CO                               3
Boulder, CO                              3
Denver, CO+2 locations                   3
Boulder, CO                              3
Colorado                                 3
Hybrid remote in Denver, CO              3
Broomfield, CO                           2
Remote in Boulder, CO                    2
Remote in Colorado Springs, CO           2
Loveland, CO                             2
Hybrid remote in Aurora, CO              2
Hybrid remote in Lone Tree, CO           2
Centennial, CO                           2
Greenwood Village, CO                    2
Boulder, CO+1 location                   2
Englewood, CO                            2
Westminster, CO                          1
Hybrid remote in Highlands Ranch, CO     1
Temporarily Remote in Englewood, CO      1
Temporarily Remote in Boulder, CO        1
Greeley, CO                              1
Colorado+3 locations                     1
Denver, CO (Virginia Village area)       1
Remote in Littleton, CO                  1
Broomfield, CO                           1
Hybrid remote in Denver, CO              1
Remote in Denver, CO+1 location          1
Remote in Boulder, CO                    1
Englewood, CO                            1
Denver, CO+4 locations                   1
Evergreen, CO                            1
Golden, CO                               1
Grand Junction, CO                       1
Remote in Louisville, CO                 1
Fort Collins, CO                         1
Name: location, dtype: int64

# Q 3 b(1.5 point) - Top 3 most demanding skills(like Python, AWS, SQL ...)

In [14]:
values = []

columns = ['Python', 'SQL', 'AWS', 'RESTFUL', 'Machine_Learning', 'Deep_Learning', 'Text_Mining', 
        'NLP', 'SAS', 'Tableau', 'Sagemaker', 'TensorFlow', 'Spark']

for i in columns:
    try: 
        values.append(job_df[i].value_counts()[1])
    except KeyError:
        values.append(0) 

columnData= {'skill': columns, 'value': values}
columnDF = pd.DataFrame(columnData)

columnDF.sort_values(by=['value'], ascending = False)
columnDF.head(3)

    skill  value
0  Python     97
1     SQL     74
2     AWS     34

# Q3 c(.5 point) What other questions you would like to ask  based on indeed data?

This is a free response question.

Required years of experience and salary range would be useful information. It would be interesting to cross reference the company with information on Glassdoor or other workplace rating/review websites to get an idea from past employees. Addtionally, you could compare the salary range with other salaries listed on industry standard websites.